### ISSUE TITLE
Error in extract.bartcFit(object, "sigma", combineChains = FALSE)

### ISSUE THREAD

**Issue by cls3415** [vdorie/bartCause#10]
Hi Vincent- 
When I ran summary function to bartcFit object I got the following error message:
binary response model does not have a residual standard deviation parameter (sigma)

My fit result is as follow:
```
Call:
bartc(response = dat2$RESPONSE, treatment = dat2$TREAT1, 
      confounders = dat2[, var1], commonSup.rule = "sd", seed = 100223, 
      n.chains = 5L)

Treatment effect (ate, cate): -0.06885
```

Any helps are appreciated!

Thanks!

**Comment by vdorie** [comment]
Thanks! Fixed in 0a02002.
