### ISSUE TITLE
KeepTrees

### ISSUE THREAD

**Issue by edgarakopyan** [vdorie/bartCause#13]
When trying to predict with a given bartcFit object I get an error 

`
Error in predict.bartcFit(bb, x_test[, , 1], type = "mu.0") : 
  predict with method.rsp = 'bart' requires response model to be fit with keepTrees == TRUE
`

However, there is not keepTrees in bartc function.  Is there any way to get those predictions?

**Comment by vdorie** [comment]
Yep! The function accepts dots-arguments that it passes on the model fitting functions. From the man page:

> `args.rsp`, `args.trt`, `...`: Further arguments to the treatment and response model fitting algorithms.  Arguments passed to the main function as `...` will be used in both models. `args.rsp` and `args.trt` can be used to set parameters in a single fit, and will override other values. See `glm` and `bart2` for  reference.

**Comment by edgarakopyan** [comment]
Thanks! I thought I tried that already and it did not work, but looks like everything is alright
